language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  global:
    - CI=true
# command to install dependencies
install:
  - pip install .
script: python tests/supervisor.py
branches:
  only:
    - master